### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [osV22/ATTACK-Force-Graph#1]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by osV22** [comment]
Hello @SkyBulk, thank you for the kind words. 

The project just got a sizeable update that includes an interactive UI to see all ATT&CK data (7d4af24e01fdce873b7e6c55df49ea77c5a76a40) and I added an MIT license (d4be4acb70d6a707c1ada4f898d013c0d2d32f16) thanks to your suggestion. 

Any more suggestions are welcomed!
